name: biodata_ugun
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.1
  http: ^0.13.4
  socket_io_client: ^2.0.0
  firebase_core: ^2.14.0
  firebase_auth: ^4.6.3
  shared_preferences: ^2.1.2
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  

flutter:
  uses-material-design: true
